-- Default forms for every practice: PHQ-9, GAD-7 and a review form.
--
-- They existed only in prisma/seed.js, which is never run in production, so no
-- real practice had any assessments. New practices now get them at signup
-- (apps/api/src/modules/intake/default-forms.ts, the source of this SQL); this
-- adds them to practices created before that. Idempotent: a practice that
-- already has a form with the same systemKey, or any review form, is skipped.

INSERT INTO "UniversalForm" ("tenantId", "title", "slug", "systemKey", "description", "targetType", "schemaJson", "reviewPublicationMode", "reviewerDisplayMode", "isDefault", "isActive", "createdAt", "updatedAt")
SELECT t."id", 'PHQ-9', 'phq-9', 'PHQ_9', 'Depression screening questionnaire. Over the last 2 weeks, how often have you been bothered by the following? 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day.', 'ASSESSMENT', '[{"id": "phq9_1", "label": "Little interest or pleasure in doing things", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_2", "label": "Feeling down, depressed, or hopeless", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_3", "label": "Trouble falling or staying asleep, or sleeping too much", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_4", "label": "Feeling tired or having little energy", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_5", "label": "Poor appetite or overeating", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_6", "label": "Feeling bad about yourself, or that you are a failure or have let yourself or your family down", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_7", "label": "Trouble concentrating on things, such as reading or watching television", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_8", "label": "Moving or speaking so slowly that other people could have noticed, or being so fidgety or restless that you have been moving around a lot more than usual", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_9", "label": "Thoughts that you would be better off dead, or of hurting yourself in some way", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}]'::jsonb, 'MANUAL', 'FIRST_NAME', true, true, NOW(), NOW()
FROM "Tenant" t
WHERE NOT EXISTS (SELECT 1 FROM "UniversalForm" f WHERE f."tenantId" = t."id" AND f."systemKey" = 'PHQ_9');

INSERT INTO "UniversalForm" ("tenantId", "title", "slug", "systemKey", "description", "targetType", "schemaJson", "reviewPublicationMode", "reviewerDisplayMode", "isDefault", "isActive", "createdAt", "updatedAt")
SELECT t."id", 'GAD-7', 'gad-7', 'GAD_7', 'Anxiety screening questionnaire. Over the last 2 weeks, how often have you been bothered by the following? 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day.', 'ASSESSMENT', '[{"id": "gad7_1", "label": "Feeling nervous, anxious, or on edge", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_2", "label": "Not being able to stop or control worrying", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_3", "label": "Worrying too much about different things", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_4", "label": "Trouble relaxing", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_5", "label": "Being so restless that it is hard to sit still", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_6", "label": "Becoming easily annoyed or irritable", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "gad7_7", "label": "Feeling afraid, as if something awful might happen", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}]'::jsonb, 'MANUAL', 'FIRST_NAME', true, true, NOW(), NOW()
FROM "Tenant" t
WHERE NOT EXISTS (SELECT 1 FROM "UniversalForm" f WHERE f."tenantId" = t."id" AND f."systemKey" = 'GAD_7');

INSERT INTO "UniversalForm" ("tenantId", "title", "slug", "systemKey", "description", "targetType", "schemaJson", "reviewPublicationMode", "reviewerDisplayMode", "isDefault", "isActive", "createdAt", "updatedAt")
SELECT t."id", 'Leave a Review', 'leave-a-review', NULL, 'Collect client testimonials for your booking page. Nothing is published until you approve it.', 'REVIEW', '[{"id": "rating", "label": "How would you rate your experience?", "type": "scale", "required": true, "options": ["1", "2", "3", "4", "5"]}, {"id": "testimonial", "label": "What stood out about your experience?", "type": "textarea", "required": false}]'::jsonb, 'MANUAL', 'FIRST_NAME', true, true, NOW(), NOW()
FROM "Tenant" t
WHERE NOT EXISTS (SELECT 1 FROM "UniversalForm" f WHERE f."tenantId" = t."id" AND f."targetType" = 'REVIEW');

-- The demo practice's PHQ-9 had only its first question.
UPDATE "UniversalForm"
   SET "schemaJson" = '[{"id": "phq9_1", "label": "Little interest or pleasure in doing things", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_2", "label": "Feeling down, depressed, or hopeless", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_3", "label": "Trouble falling or staying asleep, or sleeping too much", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_4", "label": "Feeling tired or having little energy", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_5", "label": "Poor appetite or overeating", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_6", "label": "Feeling bad about yourself, or that you are a failure or have let yourself or your family down", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_7", "label": "Trouble concentrating on things, such as reading or watching television", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_8", "label": "Moving or speaking so slowly that other people could have noticed, or being so fidgety or restless that you have been moving around a lot more than usual", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}, {"id": "phq9_9", "label": "Thoughts that you would be better off dead, or of hurting yourself in some way", "type": "single_choice", "options": ["0", "1", "2", "3"], "required": true}]'::jsonb, "description" = 'Depression screening questionnaire. Over the last 2 weeks, how often have you been bothered by the following? 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day.', "updatedAt" = NOW()
 WHERE "slug" = 'demo-phq-9' AND jsonb_array_length("schemaJson") < 9;
