#!/bin/bash
# Rewrites /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's published
# ranges, then reloads nginx — but only if the new file passes `nginx -t`.
# Safe to run from cron monthly:  0 4 1 * * /path/to/update-cloudflare-ips.sh
set -euo pipefail

TARGET=/etc/nginx/conf.d/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"

# An empty or truncated download must never replace a working list.
if [ "$(printf '%s\n' "$v4" | grep -c /)" -lt 10 ] || [ "$(printf '%s\n' "$v6" | grep -c /)" -lt 5 ]; then
    echo "Cloudflare IP lists look incomplete; leaving $TARGET unchanged." >&2
    exit 1
fi

{
    echo "# Generated by update-cloudflare-ips.sh on $(date -u +%F). See the repo copy for why."
    echo "real_ip_header CF-Connecting-IP;"
    printf '%s\n' "$v4" "$v6" | sed '/^$/d; s/^/set_real_ip_from /; s/$/;/'
} > "$TMP"

if cmp -s "$TMP" "$TARGET" 2>/dev/null; then
    exit 0
fi

cp "$TARGET" "$TARGET.bak" 2>/dev/null || true
cp "$TMP" "$TARGET"
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo "Updated $TARGET and reloaded nginx."
else
    echo "nginx -t failed with the new list; restoring the previous one." >&2
    cp "$TARGET.bak" "$TARGET"
    exit 1
fi
